- hosts: localhost
  remote_user: vagrant
  become: yes
  roles:
    - java
    - docker
    - nginx
#  tasks:
#  - name: get coreutils version
#    command: java --version
#    - books-service
#    - registry
#    - jenkins
